CREATE TABLE users (
  user_id SERIAL PRIMARY KEY,
  name VARCHAR(512) NOT NULL,
  profile VARCHAR(1024) NOT NULL,
  affiliation VARCHAR(512),
  position VARCHAR(512),
  email VARCHAR(512) NOT NULL UNIQUE,
  password VARCHAR(512) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);